###Learning Outcomes###
1. Common data imputation techniques; mean, median and mode
2. Another data imputation approach; LOCF LOCB
3. Linear interpolatopn and arbitrary values

In [56]:
import random
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from faker import Faker

In [57]:
data_housing=r'c:\Users\MURERWA DANIEL\Downloads\housing_data.csv'
df=pd.read_csv(data_housing)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\MURERWA DANIEL\\Downloads\\housing_data.csv'

EXECUTIVE SUMMARY
investigate factors influencing house sale price 

PROBLEM STATEMENT

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
df.isna().head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False

In [ ]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [ ]:
#extract data wiith missing data
data_housing_001=df[df.notnull().all(axis=1)]
data_housing_001.isnull().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [ ]:
#data cleaned
df_clean=df[df.notnull().all(axis=1)]
df_clean.isna().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

dealing with missing data in balcony

In [ ]:
#the data is missing at random
#this is mising because of observed values
#Action: input 0 where house is missing a balcony

df_new=df.copy()
df_new

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [ ]:
df_new['balcony'].value_counts()
#inputing 0 not an idea since some zeroes exist

balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64

In [ ]:
#Another Approach:
df_new1=df.copy()
new_df=df_new1['balcony'].fillna(-999)
new_df.value_counts()

balcony
 2.0      5113
 1.0      4897
 3.0      1672
 0.0      1029
-999.0     609
Name: count, dtype: int64

Looking at the table for the bath with 73 missing values

In [ ]:
#missing during the entry?
df_new1['bath'].isna().sum()
df_new1['bath'].value_counts()

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64

Generate Randm data

In [58]:
num_of_patients=100
data={
    'PatientId':[f"PId_{i:03d}" for i in range(1, num_of_patients + 1)],
    'Name':[fake.name( for _ in range(num_of_patients))],
    "Age":np.random.normal(45,15, num_of_patients).astype(int).clip(50,120),
    'Blood Pressure _Diastolic':np.random.normal(80,10, num_of_patients).astype(int).clip(60,120),
    'Cholestrol':np.random.normal(200,30, num_of_patients).astype(int).clip(150,300),
    'Blood Pressure _Systolic':np.random.normal(120,15, num_of_patients).astype(int).clip(90,180),
    'BMI':np.random.normal(25,5, num_of_patients).astype(float).clip(15,40),
    'Glucose':np.random.normal(100,15, num_of_patients).astype(float).clip(70,150),
    'Smoker':np.random.choice(['Yes', 'No'], num_of_patients, p= [0.3, 0.7])
}

SyntaxError: invalid syntax (3961616871.py, line 4)

In [59]:
#introduce missing data noise
missing_patterns={
    'Blood_pressure_systolic':0.1,  # 10% missing
    'Blood_pressure_diastolic':0.15,  # 15% missing
    'BMI':lambda x:0.2 if x['Age']<30 else 0.5,  # 20% missing for age < 30, 50% for age >= 30
    'Cholestrol':0.15,  # 15% missing
    'Glucose':lambda x: 0.3 if x['Smoker']=='No' else 0.1 # 10% missing
}

In [61]:
for col, pattern in missing_patterns.items():
    if callable(pattern):
        mask=data_patients.apply(pattern, axis=1)>np.random.rand(len(data_patients))
    else:
        mask=np.random.rand(len(data_patient))<pattern

    data_patients.loc[mask, col]=np.nan

NameError: name 'data_patient' is not defined